events { worker_connections 1024; }

http {
    upstream mlops_api {
        least_conn;
        server api-1:8000;
        server api-2:8000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://mlops_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
